export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  RESERVATION_MANAGER = 'RESERVATION_MANAGER',
  DELIVERY_AGENT = 'DELIVERY_AGENT',
}

export const ADMIN_ACCESS_ROLES = [Role.SUPER_ADMIN, Role.ADMIN];
